### ISSUE TITLE
Execute migrate-up with error

### ISSUE THREAD

**Issue by millionfor** [cyberinferno/koa-ts-template#1]
npx ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'quanquan_test' AND `TABLE_NAME` = 'migrations'
query: CREATE TABLE `migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
query: SELECT * FROM `quanquan_test`.`migrations` `migrations` ORDER BY `id` DESC
0 migrations are already loaded in the database.
2 migrations were found in the source code.
2 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'quanquan_test' AND `TABLE_NAME` = 'profile'
query: CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB
query failed: CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB
error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1
    at Query.Sequence._packetToError (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    --------------------
    at Protocol._enqueue (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/src/driver/mysql/MysqlQueryRunner.ts:172:36)
    at step (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1`,
  sqlState: '42000',
  index: 0,
  sql: 'CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT \'{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}\', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
}
Migration "ProfileTable1641286704730" failed, error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1
query: ROLLBACK
Error during migration run:
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1
    at QueryFailedError.TypeORMError [as constructor] (/Users/gongzijian/WebstormProjects/github/qq-robot-new/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/gongzijian/WebstormProjects/github/qq-robot-new/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/src/driver/mysql/MysqlQueryRunner.ts:183:37)
    at Query.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  query: 'CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT \'{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}\', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
  parameters: undefined,
  driverError: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1
      at Query.Sequence._packetToError (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      --------------------
      at Protocol._enqueue (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/mysql/lib/Connection.js:198:25)
      at MysqlQueryRunner.<anonymous> (/Users/gongzijian/WebstormProjects/github/qq-robot-new/src/driver/mysql/MysqlQueryRunner.ts:172:36)
      at step (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:143:27)
      at Object.next (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/Users/gongzijian/WebstormProjects/github/qq-robot-new/node_modules/tslib/tslib.js:114:62)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1`,
    sqlState: '42000',
    index: 0,
    sql: 'CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT \'{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}\', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
  },
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL DEFAULT '{"salutation":"Mr","firstName":"","middleName":"","lastNa' at line 1`,
  sqlState: '42000',
  index: 0,
  sql: 'CREATE TABLE `profile` (`id` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `data` json NOT NULL DEFAULT \'{"salutation":"Mr","firstName":"","middleName":"","lastName":"","dateOfBirth":""}\', `meta` json NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX `UQ_d80b94dc62f7467403009d88062` (`username`), PRIMARY KEY (`id`)) ENGINE=InnoDB'
}
error Command failed with exit code 1.

What is the problem with mysql version 5.6 ？

**Comment by cyberinferno** [comment]
MySQL version 5.6 does not have JSON column support. Use MySQL version 5.7.8 or above!
